### ISSUE TITLE
Support non-nested arrays?

### ISSUE THREAD

**Issue by jd20** [mattphillips/jest-each#4]
It seems something like this should work:

```
describe('test numbers', () => {
  each([2, 1, 0]).test('test %s', (expected) => {
    expect(typeof expected).toBe('number')
  })
})
```

But `expected` will be `undefined`, the array has to be rewritten as `[[2], [1], [0]]`. Would it maybe make more sense to check if the parameters are not iterable or an array, and wrap them appropriately? The resulting test code would look a lot cleaner.

**Comment by mattphillips** [comment]
Hey @jd20 I'm not sure your example makes sense in all cases.

Currently jest-each requires an Array of Arrays for the data. This is because the data is essentially a table, with rows and columns. Where each row represents a test, and each column represents an argument to the test function.

Given your example,

```js
[[2], [1], [0]]
```
is equivalent to 

| index  | expected |
| -- |:-------------:|
| 0  | 2 |
| 1   | 1 |
| 2  | 0 |
---

The issue with dropping the inner arrays (row of columns) and wrapping them internally is that not all tests have one argument. When they do have one argument that arg may just be an `Array` so jest-each wouldn't be able to determine if that should be wrapped or passed into the test as columns.

For example:

```js
describe('test arrays', () => {
  each([[], [0], [1]]).test('test %s', (expected) => {
    expect(Array.isArray(expected)).toBe(true)
  })
})
```
jest-each wouldn't know what to do with this test.

---

I wouldn't be opposed to dropping the outer array (table) and just splat the rows into `each(rows)`. For example:

```js
describe('test numbers', () => {
  each([2], [1], [0]]).test('test %s', (expected) => {
    expect(typeof expected).toBe('number')
  })
})
```

This way the API stays consistent, you always supply your row arguments in an array (both for one or more args) and don't need the outer table array.

Let me know what you think 😄

**Comment by jd20** [comment]
Right, so with the columns / rows analogy you make, if we're passed a 1D array (instead of 2D) wouldn't it be unambiguous to convert that to a single-column table? (Single row wouldn't make sense, since you're calling `each`, presumably you want to run more than one test.)

I tried making the change myself: https://github.com/jd20/jest-each/commit/d69beabb51f37d6d37b27b65f5c96a70c78b8bbe. Running locally, all tests still pass. Is there a specific case you were thinking of, that would cause it to fail?

**Comment by mattphillips** [comment]
I've just updated my original message the analogy deviated towards the end 🤣 

> Right, so with the columns / rows analogy you make, if we're passed a 1D array (instead of 2D) wouldn't it be unambiguous to convert that to a single-column table? (Single row wouldn't make sense, since you're calling each, presumably you want to run more than one test.)

What I mean is currently `each` takes a table (2D array). I'd be happy to change this table to use [varargs/ ...rest](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) of arrays.

For example:
```js
describe('add', () => {
  each([
    [2, 1, 1],
    [1, 1, 0],
    [0, 0, 0]
  ]).test('returns %s when given %s and %s', (expected, a, b) => {
    expect(a + b).toBe(expected)
  })
})
```
This test would become:

```js
describe('add', () => {
  each(
    [2, 1, 1],
    [1, 1, 0],
    [0, 0, 0]
  ).test('returns %s when given %s and %s', (expected, a, b) => {
    expect(a + b).toBe(expected)
  })
})
```
_Note the outer array is not needed._

---

For your use case of wrapping an indivdual value in an array to make it a row with one column the issue I see is with `Array` values.

For example this currently works:
```js
describe('array', () => {
  each([ // this array is the table
    [ // this array is a row
      [2, 4, 6] // this is a single column to be passed into the test as the `array` variable
    ],
    [
      []
    ],
    [
      [10]
    ],
  ]).test('%s does not contain any odd numbers', (array) => {
    expect(array.every(n => n % 2 == 0)).toBe(true);
  })
})
```

If we removed the requirement for the row array for single cols the above test could be written like this:

```js
describe('array', () => {
  each([ // this array is the table
    [2, 4, 6], // this is a single column to be passed into the test as the `array` variable
    [],
    [10],
  ]).test('%s does not contain any odd numbers', (array) => {
    expect(array.every(n => n % 2 == 0)).toBe(true);
  })
})
```
It wont work because jest each wont wrap an array as a single column and will instead spread that arrays contents into the test. It will be ran as:
 1. `array` = 2
 2. `array` = undefined
 3. `array` = 10

<img width="629" alt="screen shot 2018-04-19 at 09 37 23" src="https://user-images.githubusercontent.com/5610087/38980681-655415ee-43b5-11e8-8dc2-4a649f276cfd.png">

**Comment by mattphillips** [comment]
@jd20 this is now possible in jest-each@23 or inside of core Jest@23 with `test.each` see https://facebook.github.io/jest/docs/en/api.html#testeachtable-name-fn

**Comment by jd20** [comment]
Awesome, thank you for the heads up!

**Comment by Dobby89** [comment]
Is there any way of supporting one dimensional arrays and re-using the template strings so they can be used more than once in the test description? I want to be able to do this:

```javascript
function greeting(name) {
  return `Hello, ${name}`;
}

it.each(['John', 'Jane'])('should return "Hello, %s" when given "%s"', name => {
  expect(greeting(name)).toEqual(`Hello, ${name}`);
});
```

Output would be...

```
should return "Hello, John" when given "John"
should return "Hello, Jane" when given "Jane"
```

Currently it seems the only way to achieve this is to use multidimensional arrays, which seems awkward.

```javascript
it.each([['John', 'John'], ['Jane', 'Jane']])('should return "Hello, %s" when given "%s"', name => {
  expect(greeting(name)).toEqual(`Hello, ${name}`);
});
```

#### Updated with solution:

See https://jestjs.io/docs/en/api#describeskipeach-table-name-fn

```javascript
it.each`
	name
	${'John'}
	${'Jane'}
`(
	'should return "Hello, $name" when given "$name"',
	({ name }) => { // Note, it must be an object
		expect(greeting(name)).toEqual(`Hello, ${name}`);
	}
);
```
