### ISSUE TITLE
support for setup and teardown methods

### ISSUE THREAD

**Issue by dainchatel** [mattphillips/jest-each#6]
thanks for a great library, matt! this might be more of a feature request, but i'm having a hard time defining the array i pass into each() in the global jest setup methods, specifically beforeAll. at first i thought it had something to do with async request i was making in the beforeAll, but then I realized this doesn't work either:

```
describe('test suite', () => {
  let products

  beforeAll(() => {
    products = [['def', '321'], ['abc', '123']]
  })

  describe('in here now', () => {
    each(products).test('test %s', (name, id) => {
      expect(id).toBe(id)
    })
  })
```

I get 'TypeError: Cannot read property 'forEach' of undefined' on the line where each() is called. i tried it inside and outside its own describe block, and no luck. have you noticed a similar issue? apologies if I missed something obvious. thanks again.

**Comment by mattphillips** [comment]
Hey @dainchatel I suspect the issue is because when `each` is being evaluated the `products` array is still `undefined`.

I've knocked up a quick example in a [Jest repl here](https://repl.it/@mattphillipsio/issue-6)

The example just uses log statements instead of `each`

```js
describe('test suite', () => {
  let products

  beforeAll(() => {
    products = [['def', '321'], ['abc', '123']]
  })

  describe('in here now', () => {
    console.log('No products', products)
    
    test('this should log the products', () => {
      console.log('Products:', products);
    })
  })
})
```

As you will see when you run the repl the outer log with be `undefined` with the one inside of the test being the actual array. This is because Jest is internally preventing the execution of the test callback function until the `beforeAll` is run.

It appears that the inner `describe` callback is evaluated immediately but not the nested `test`s which means the `console.log` or `each` function is also evaluated immediately so we are unable to wait on the global setup hooks (`beforeAll` etc).

I'm not sure there is a way around this unfortunately.

It might be worth asking a question in a core Jest channel to see if a `describe` block should wait for the `beforeAll` to finish before being executed?

**Comment by dainchatel** [comment]
thanks, @mattphillips! I really appreciate your answer. I came to the same conclusion, and may go see what the main jest channel has to say about whether nested describe blocks should wait for a beforeAll. But for deadline's sake, just ended up loading my products synchronously. Since it's not an issue with jest-each I will close. Thanks again-
